### ISSUE TITLE
Error Running on Large SQL Server Dataset

### ISSUE THREAD

**Issue by ijabit** [Azure/azure-documentdb-datamigrationtool#27]
I've written two conversion jobs using dt.exe and they work good. But this third conversion is running over some 15 million rows which are being joined to two other tables of similar size. All operations are index seeks and statistics are updated so the query is as fast as I can get it. I can pull 100,000 rows in about 2 minutes. It works fine from my local desktop but when I run it in an Azure webjob I get timeouts:

```[05/26/2017 22:26:50 > f507cd: INFO] Transferred: 0; Failed: 0; Elapsed Time: 00:00:30.0208549
[05/26/2017 22:26:50 > f507cd: INFO] Critical error: System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
[05/26/2017 22:26:50 > f507cd: INFO]    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[05/26/2017 22:26:50 > f507cd: INFO]    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[05/26/2017 22:26:51 > f507cd: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at Microsoft.DataTransfer.Sql.Source.SqlQueryDataSourceAdapter.<ExecuteCommand>d__6.MoveNext()
[05/26/2017 22:26:51 > f507cd: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at Microsoft.DataTransfer.Sql.Source.SqlQueryDataSourceAdapter.<InitializeAsync>d__3.MoveNext()
[05/26/2017 22:26:51 > f507cd: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at Microsoft.DataTransfer.Sql.Source.SqlDataSourceAdapterFactory.<CreateAsync>d__0.MoveNext()
[05/26/2017 22:26:51 > f507cd: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at Microsoft.DataTransfer.Core.Service.DataTransferService.<TransferAsync>d__9.MoveNext()
[05/26/2017 22:26:51 > f507cd: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/26/2017 22:26:51 > f507cd: INFO]    at Microsoft.DataTransfer.ConsoleHost.App.Handlers.OneTimeDataTransferHandler.<RunAsync>d__0.MoveNext()
[05/26/2017 22:26:51 > f507cd: INFO] ClientConnectionId:c4525372-6130-46da-b1c0-9ce3a0b518bc
[05/26/2017 22:26:51 > f507cd: INFO] Error Number:-2,State:0,Class:11
[05/26/2017 22:26:51 > f507cd: INFO] ClientConnectionId before routing:8d800724-a675-4257-b93b-368ef2eb3268
[05/26/2017 22:26:51 > f507cd: INFO] Routing Destination:b6708a35bc8a.tr29.eastus1-a.worker.database.windows.net,11026
[05/26/2017 22:26:51 > f507cd: INFO] 
[05/26/2017 22:26:51 > f507cd: INFO] DocumentDB Data Migration Tool v1.7.0.0
[05/26/2017 22:26:51 > f507cd: INFO] ```

So it seems to open the connection just fine but then time out waiting for results. Is there a setting to increase or ignore the timeout? I tried adding Timeout=300 to the connection string but that only seems to apply to the connection timeout, where this is waiting for results. It seems that a bulk import tool should be able to run for hours importing without timing out?

**Comment by nahk-ivanov** [comment]
Hi,

Yeah, we probably should expose the `CommandTimeout` property, so that you can set it to zero and hope for best. The thing is - in case of SQL Server source it will try to hold the connection for the entire import reading the data, so "run for hours" essentially means no network glitches in hours. Most of other sources support pagination on the protocol level, so they are more reluctant to transient network issues.

There are two ways how you can work-around this today:

1. Update your script to do preliminary data partitioning and call `dt.exe` for each partition (you probably will be able to do this in parallel, depending on the throughput of source and target).
2. Put the `command.CommandTimeout = 0;` in [here](https://github.com/Azure/azure-documentdb-datamigrationtool/blob/master/Sql/Microsoft.DataTransfer.Sql/Source/SqlQueryDataSourceAdapter.cs#L37) at line 37, right after `command = ...`, recompile and hope for best.

I think it's still good to expose command timeout as a configurable property, will try to add it in the next version. I'm actually surprised this is the first time we are getting this feedback through all these years.

Regards,
Alex.

**Comment by ijabit** [comment]
Thank you for those work-around's. I'll give them a try. I actually start getting results in a couple of minutes so increasing the timeout to 300 or something should be good enough.

**Comment by garfbradaz** [comment]
Was the timeout either exposed @nahk-ivanov ?

**Comment by nahk-ivanov** [comment]
Hi,

The code still seems to be the same. I don't think there were any improvements done in that area.

Regards,
Alex.

**Comment by garfbradaz** [comment]
@nahk-ivanov : I will try and get a PR and expose this via the UI. Do you know if any of the data sources would need Timeout added?

**Comment by nahk-ivanov** [comment]
Hi,

I think most of them retrieve data in batches, so depending on the retry logic (where exists) - it can just reconnect and continue enumeration with some previous token. Some of them probably don't even have a timeout.

I'd just do SQL Server, as we've already seen cases where it was needed.

Regards,
Alex.

**Comment by Eshayat** [comment]
I'm getting the same error. My query takes 2:30 secs to run and creating partitioning and the temporary table will take a long time.
Can I get a build with no timeout from the SQL Server side?

Thanks
